<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnitAssemblySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $units =[
                [
                    'complete_description' => 'ISUZU',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'FAW',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SINOTRUK CDW',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'MAXPOWER',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'YAMAHA',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SHANTUI',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'KIA',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SINOTRUK CDW',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SINOTRUK HOMAN',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'TOKYU',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'HYUNDAI',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'ISUZU',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SINOTRUK HOWO',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'MITSUBISHI',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'NISSAN',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SINOMACH',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'ASTRA HEAVY',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'LAIGONG',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'CHANGLIN',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'XCMG',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'XCMG',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'JINGGONG',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'TONGYA',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'LIFAN',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'ZOOMLION',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'FORD RANGER',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'CIMC',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'TOYOTA',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'DADOM',
                    'a_type'      => 'Equipment',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'XCMG',
                    'a_type'      => 'Attachment',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'DONGFENG',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'ISUZU D-MAX',
                    'a_type'      => 'Special',
                    'remarks' => 'Make',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],


                // cabin

                [
                    'complete_description' => '600P',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'AH916H',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => '-',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'J6P',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'J6M',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => '757',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => '737',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => '777',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'J6F',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'L46',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'AH955H',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'J6B',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SE210W-L',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SE135W',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SG14-B5',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'J6L',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'AH821M',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'AH935H',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'DHL',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'KV100',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'L36-B3',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'GIGA',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'L16',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'AH806M',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'FTR 4HK1',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'MEGA',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => '700P',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'H3',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => '-',
                    'a_type'      => 'Equipment',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => '150W',
                    'a_type'      => 'Attachment',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'H135G',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'REGA',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'complete_description' => 'H3',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'YTX125',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SE60Y',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => '100P',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'L200',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'NAVARRA CALIBRE',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => '757',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => '737 EXTENDED',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'L55-B5',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'FVZ',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SE60W',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'CPD20',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'ME50W',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SE210W',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SD26',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'AH821M',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => '-',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'LG946',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SZ16',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'NPR',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SE137W',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'LG936',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'LGE56',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'L36-B5',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'L56',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => '955T',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => '956T',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'WZ30-25',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'AH308LG',
                    'a_type'      => 'Equipment',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'L36-B3',
                    'a_type'      => 'Attachment',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'ME60-9',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'ME205.9',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],


                [
                    'complete_description' => 'GHT160W',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SE355W',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'GHT160W',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SR06MA',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'XS600J',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SG10-B5',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SG12',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SG17-B6',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'GR1003',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'AH803LG',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SE135-A',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SE137-9W',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SD22',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'JG708S',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'AH818M',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'AH805W',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'A7',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'J6F VN',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SRD03',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'LFJ1036T1',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'ME18-9',
                    'a_type'      => 'Equipments',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'J6F VR',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'J6F VH',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SD16',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'DH08-B2 XL',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'DH10-B2 XL',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SD13',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SD32',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'DH46-C3',
                    'a_type'      => 'Equipment',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'SD60-C5',
                    'a_type'      => 'Attachment',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'GHT50',
                    'a_type'      => 'Trucks',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'complete_description' => 'GHT80',
                    'a_type'      => 'Special',
                    'remarks' => 'Cabin',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

        ];
        DB::table('ir_shipment_unit_assembly')->insert($units);
    }
}
