<x-app-layout title="AstraMC Trucks & Equipments">

    {{-- ── Breadcrumb ──────────────────────────────────────────────────────── --}}
    <div class="mb-5">
        <x-breadcrumb :items="[
            ['label' => 'Dashboard',      'active' => false],
            ['label' => 'Human Resource', 'active' => false],
            ['label' => 'Employees',      'active' => true],
        ]" />
    </div>

    @php
        $styles = [
            'label'    => 'block text-[0.68rem] font-bold uppercase tracking-widest text-gray-400 mb-1',
            'input'    => 'w-full px-3 py-2.5 text-sm rounded-lg border border-gray-200 bg-white text-gray-800
                           transition duration-150 focus:outline-none focus:border-blue-500 focus:ring-2
                           focus:ring-blue-100 placeholder:text-gray-300',
            'readonly' => 'w-full px-3 py-2.5 text-sm rounded-lg border border-orange-300 bg-gray-100
                           text-gray-400 font-mono cursor-not-allowed focus:outline-none select-none',
            'compact'  => 'h-8 text-xs',
            'error' => 'border-red-500 text-red-500 text-[10px] mt-0.5 leading-none',
        ];

        $leaveTypes = [
            'vl' => ['label' => 'VL'],
            'sl' => ['label' => 'SL'],
            'bl' => ['label' => 'BL'],
            'el' => ['label' => 'EL'],
            'ml' => ['label' => 'ML'],
            'pl' => ['label' => 'PL'],
        ];

        $workDays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];


        $autoGeneratedBadge = '<span class="ml-1 text-[0.58rem] font-medium normal-case tracking-normal
                    text-blue-500 bg-blue-50 px-1.5 py-0.5 rounded-full">Auto-generated</span>';

        $hsSelectConfig = json_encode([
            'placeholder'        => 'Select branch...',
            'mode'               => 'tags',
            'wrapperClasses'     => 'relative ps-0.5 pe-9 min-h-11.5 flex items-center flex-wrap text-nowrap w-full bg-white dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-lg text-start text-sm focus:border-blue-700 dark:focus:border-blue-600',
            'dropdownClasses'    => 'mt-2 z-50 w-full max-h-72 p-1 space-y-0.5 bg-white dark:bg-neutral-900 border border-transparent rounded-lg shadow-xl overflow-hidden overflow-y-auto',
            'optionClasses'      => 'py-2 px-4 w-full text-sm text-gray-800 dark:text-neutral-200 cursor-pointer hover:bg-blue-100 dark:hover:bg-neutral-800 rounded-lg focus:outline-hidden',
            'tagsItemTemplate'   => '<div class="flex flex-nowrap items-center relative z-10 bg-white dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-full p-1 m-1"><div class="whitespace-nowrap text-gray-800 dark:text-neutral-200" data-title></div><div class="inline-flex shrink-0 justify-center items-center size-5 ms-2 rounded-full bg-gray-100 dark:bg-neutral-700 hover:bg-gray-200 dark:hover:bg-neutral-600 text-sm cursor-pointer" data-remove><svg class="shrink-0 size-3" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg></div></div>',
            'tagsInputClasses'   => 'py-2.5 px-2 min-w-20 rounded-lg order-1 bg-transparent border-transparent text-gray-800 dark:text-neutral-200 placeholder:text-gray-500 focus:ring-0 text-sm outline-hidden',
            'optionTemplate'     => '<div class="flex items-center"><div class="text-sm text-gray-800 dark:text-neutral-200" data-title></div><div class="ms-auto"><span class="hidden hs-selected:block"><svg class="shrink-0 size-4 text-blue-600" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425z"/></svg></span></div></div>',
            'extraMarkup'        => '<div class="absolute top-1/2 end-3 -translate-y-1/2"><svg class="shrink-0 size-3.5 text-gray-500" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m7 15 5 5 5-5"/><path d="m7 9 5-5 5 5"/></svg></div>',
        ]);
    @endphp

    {{-- ── FIX 1: previewImage() defined here ─────────────────────────────── --}}
    <script>
        function previewSignature(event) {
            const file = event.target.files[0];
            if (!file) return;

            const reader = new FileReader();
            reader.onload = function (e) {
                const preview     = document.getElementById('profile-preview');
                const placeholder = document.getElementById('signature-placeholder');

                preview.src = e.target.result;
                preview.classList.remove('hidden');
                placeholder.classList.add('hidden');
            };
            reader.readAsDataURL(file);
        }

        // FIX 3: Select-All properly dispatches 'change' so CSS peer state updates
        function toggleAllDays(checked) {
            document.querySelectorAll('.day-checkbox').forEach(cb => {
                if (cb.checked !== checked) {
                    cb.checked = checked;
                    cb.dispatchEvent(new Event('change'));
                }
            });
        }

        document.addEventListener("DOMContentLoaded", function () {
            const select = document.getElementById("branch-select");

            select.addEventListener("change", function () {
                const selectedValues = Array.from(select.selectedOptions).map(option => option.value);

                console.log(selectedValues); // array of selected branch ids
            });
        });

     function onChangeValue() {
        const select = document.getElementById('selectedValue');
        const selectedOption = select.options[select.selectedIndex];

        if (selectedOption && selectedOption.value !== "") {
            const { employeeId, status, position, company, name } = selectedOption.dataset;

            document.getElementById("employeeInput").value = employeeId;
            document.getElementById("statusValue").textContent = status;
            document.getElementById("positionInput").value = position;
            document.getElementById("companyInput").value = company;
            //default login details
            document.getElementById("employeeName").value = name;
            document.getElementById("employeePass").value = employeeId;
        }
        else {
            document.getElementById("employeeInput").value = "--";
            document.getElementById("statusValue").textContent = "--";
            document.getElementById("positionInput").value = "--";
            document.getElementById("companyInput").value = "--";
            //default login details
            document.getElementById("employeeName").value = "--";
            document.getElementById("employeePass").value = "";
        }
    }

    </script>

    <form action="{{ route('user-accounts.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="space-y-4">

            {{-- ══════════════════════════════════════════════════════════════ --}}
            {{-- Card: Personal Background                                      --}}
            {{-- ══════════════════════════════════════════════════════════════ --}}
            <div class="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">

                {{-- ── Header ──────────────────────────────────────────────────────────────── --}}
                <div class="flex flex-wrap items-center gap-3 px-6 py-4 border-b border-gray-100 bg-gray-50/60">

                    <x-prev-link href="{{ route('user-accounts.index') }}" aria-label="Back to Users Table">
                        <x-prevIcon />
                    </x-prev-link>

                    <div class="flex items-center gap-3">
                        <span class="flex items-center justify-center w-9 h-9 rounded-xl bg-orange-50 text-orange-500 shadow-sm"
                            aria-hidden="true">
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none"
                                viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                            </svg>
                        </span>
                        <div>
                            <h1 class="text-sm font-semibold text-gray-800 leading-tight">New User Account</h1>
                            <p class="text-[0.7rem] text-gray-400 mt-0.5">Fill in the details below to create an account</p>
                        </div>
                    </div>

                    <x-badge.status id="statusValue" color="yellow" label="Pending" class="ml-auto" />
                </div>

                {{-- ── Section Label ──────────────────────────────────────────────────────── --}}
                <div class="flex items-center gap-3 px-6 pt-6 pb-1">
                    <span class="text-[0.65rem] font-bold uppercase tracking-widest text-gray-400 whitespace-nowrap">
                        User Information
                    </span>
                    <span class="flex-1 h-px bg-orange-200" aria-hidden="true"></span>
                </div>

                {{-- ── Form Body ──────────────────────────────────────────────────────────── --}}
                <div class="px-6 py-5">
                    <div class="flex flex-col lg:flex-row gap-6">

                        {{-- ── Left: Fields Grid ──────────────────────────────────────────── --}}
                        <div class="flex-1 min-w-0">
                            <div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-x-4 gap-y-4">

                                {{-- Employee Name --}}
                                <div class="flex flex-col gap-1">
                                    <label class="{{ $styles['label'] }}">Employee Name</label>
                                    <x-forms.select-field
                                        id="selectedValue"
                                        name="employee_name"
                                        class="{{ $styles['compact'] }}"
                                        onchange="onChangeValue()"
                                    >
                                        <option value="">Select Employee</option>
                                        @foreach($employees as $employee)
                                            <option
                                                value="{{ $employee->employee_id }}"
                                                data-employee-id="{{ $employee->employee_id }}"
                                                data-status="{{ $employee->emp_status }}"
                                                data-position="{{ $employee->position?->position_description }}"
                                                data-company="{{ $employee->company?->company_name }}"
                                                data-name="{{ $employee->first_name }} {{ $employee->last_name }}"
                                            >
                                                {{ $employee->first_name }} {{ $employee->last_name }}
                                            </option>
                                        @endforeach
                                    </x-forms.select-field>
                                </div>

                                {{-- Employee ID --}}
                                <div class="flex flex-col gap-1">
                                    <label class="{{ $styles['label'] }}">
                                        Employee ID {!! $autoGeneratedBadge !!}
                                    </label>
                                    <input
                                        id="employeeInput"
                                        type="text"
                                        name="employee_id"
                                        readonly
                                        class="{{ $styles['readonly'] }} {{ $styles['compact'] }}"
                                    />
                                </div>

                                {{-- Position --}}
                                <div class="flex flex-col gap-1">
                                    <label class="{{ $styles['label'] }}">
                                        Position {!! $autoGeneratedBadge !!}
                                    </label>
                                    <input
                                        id="positionInput"
                                        type="text"
                                        name="position"
                                        readonly
                                        placeholder="—"
                                        class="{{ $styles['readonly'] }} {{ $styles['compact'] }}"
                                    />
                                </div>

                                {{-- Role --}}
                                <div class="flex flex-col gap-1">
                                    <label class="{{ $styles['label'] }}">Role</label>
                                    <x-forms.select-field name="role" class="{{ $styles['compact'] }}">
                                        <option value="">Select Role</option>
                                        @foreach($user_roles as $role)
                                            <option value="{{ $role->row_id }}">
                                                {{ $role->role_description }}
                                            </option>
                                        @endforeach
                                    </x-forms.select-field>
                                </div>

                                {{-- Company --}}
                                <div class="flex flex-col gap-1 sm:col-span-4">
                                    <label class="{{ $styles['label'] }}">
                                        Company {!! $autoGeneratedBadge !!}
                                    </label>
                                    <input
                                        id="companyInput"
                                        type="text"
                                        name="company"
                                        readonly
                                        placeholder="—"
                                        class="{{ $styles['readonly'] }} {{ $styles['compact'] }}"
                                    />
                                </div>

                                {{-- Branch --}}
                                {{-- Branch --}}
                                <div class="flex flex-col gap-1 sm:col-span-4">
                                    <label class="{{ $styles['label'] }}" for="branch-select">Branch</label>
                                    <select
                                        id="branch-select"
                                        name="branch_ids[]"
                                        multiple
                                        class="hidden"
                                        data-hs-select="{{ $hsSelectConfig }}"
                                    >
                                        <option value="">Select branch...</option>
                                        @foreach($branches as $rowId => $branchName)
                                            <option
                                                value="{{ $rowId }}"
                                                @selected(in_array((string) $rowId, old('branch_ids', [])))
                                            >
                                                {{ $branchName }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        {{-- ── Right: Signature Upload ─────────────────────────────────── --}}
                        <div class="w-full lg:w-44 flex-shrink-0">
                            <div class="border border-dashed border-gray-300 rounded-xl p-3 flex flex-col items-center gap-3
                                        bg-gray-50/50 hover:bg-orange-50/30 hover:border-orange-300 transition-colors duration-200">

                                {{-- Preview --}}
                                <div id="signature-preview-wrapper"
                                    class="w-full h-32 rounded-lg bg-white border border-gray-200 flex items-center justify-center overflow-hidden">
                                    <img
                                        id="profile-preview"
                                        src=""
                                        alt="Signature preview"
                                        class="hidden w-full h-full object-contain p-1"
                                    />
                                    <span id="signature-placeholder" class="flex flex-col items-center gap-1 text-gray-300">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8" fill="none"
                                            viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
                                            <path stroke-linecap="round" stroke-linejoin="round"
                                                d="M15.232 5.232l3.536 3.536M9 11l6.586-6.586a2 2 0 112.828 2.828L11.828
                                                    13.828A4 4 0 019 15H7v-2a4 4 0 012.172-3.586z" />
                                        </svg>
                                        <span class="text-[0.65rem] text-center leading-tight text-gray-400">
                                            No signature<br>uploaded
                                        </span>
                                    </span>
                                </div>

                                {{-- Hidden file input --}}
                                <input
                                    type="file"
                                    id="esignature"
                                    name="esignature"
                                    accept="image/*"
                                    class="hidden"
                                    onchange="previewSignature(event)"
                                />

                                {{-- Upload button --}}
                                <button
                                    type="button"
                                    onclick="document.getElementById('esignature').click()"
                                    class="w-full bg-orange-500 hover:bg-orange-600 active:bg-orange-700
                                        text-white text-xs font-semibold py-2 px-3 rounded-lg
                                        transition-colors duration-150 flex items-center justify-center gap-1.5 shadow-sm"
                                >
                                    <svg xmlns="http://www.w3.org/2000/svg" class="w-3.5 h-3.5" fill="none"
                                        viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
                                    </svg>
                                    Upload Signature
                                </button>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
            {{-- /card: personal background --}}

            {{-- ══════════════════════════════════════════════════════════════ --}}
            {{-- Card: Employment Information                                   --}}
            {{-- ══════════════════════════════════════════════════════════════ --}}
            <div class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
                <x-cards.accent-header icon="lock" title="Login Credentials" badge="EMP-RECORD" />
            <div class="px-6 pt-5 pb-6 space-y-6">
                {{-- Section: Tenure --}}
                <div>
                    {{-- <x-cards.section-label label="Tenure" /> --}}
                    <div class="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-3">
                        <div class="flex flex-col gap-1">
                            <label class="{{ $styles['label'] }}">
                                username
                            </label>
                            <input id="employeeName" type="text" name="name"
                                class="{{ $styles['input'] }} {{ $styles['compact'] }}" />
                            @error('name')
                                <p class="text-xs text-red-500">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="flex flex-col gap-1">
                            <label class="{{ $styles['label'] }}">
                                password
                            </label>
                            <input id="employeePass" type="password" name="password"
                                class="{{ $styles['input'] }} {{ $styles['compact'] }}" />
                            @error('password')
                                <p class="text-xs text-red-500">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="flex flex-col gap-1">
                            <label class="{{ $styles['label'] }}">
                                confirm password
                            </label>
                            <input type="password" name="confirm_password"
                                class="{{ $styles['input'] }} {{ $styles['compact'] }}" />
                            @error('confirm_password')
                                <p class="text-xs text-red-500">{{ $message }}</p>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
        </div>

            {{-- /card: employment information --}}


            {{-- ── Footer Actions ──────────────────────────────────────────── --}}
            <div class="flex items-center justify-end gap-2 pt-1 pb-4">
                <button type="submit"
                        class="inline-flex items-center gap-2 px-7 py-2.5 text-sm font-semibold text-white
                               bg-blue-600 rounded-lg shadow-sm shadow-blue-200 transition
                               hover:bg-blue-700 hover:shadow-blue-300 active:scale-[0.98]">
                    Save
                </button>
            </div>
        </div>{{-- /space-y-4 --}}
    </form>

</x-app-layout>
